version: '3.9'

services:
  merchant:
    image: merchant
    container_name: merchant
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - "${APP_SERVER__PORT}:${APP_SERVER__PORT}"
    networks:
      - server-side
    depends_on:
      - postgres-db
      - redis-db
    env_file: ./.env
    volumes:
      - app_data:/logs

  postgres-db:
    image: "postgres:latest"
    container_name: postgres-database
    restart: always
    networks:
      - server-side
    environment:
      - POSTGRES_USER=${APP_DB__USERNAME}
      - POSTGRES_PASSWORD=${APP_DB__PASSWORD}
      - POSTGRES_DB=${APP_DB__DATABASE_NAME}
      - POSTGRES_HOST=${APP_DB__HOST}
    ports:
      - "${APP_DB__PORT}:${APP_DB__PORT}"
  redis-db:
    image: "redis:latest"
    container_name: redis-database
    restart: always
    networks:
      - server-side
    environment:
      - REDIS_USER=${APP_REDIS__USERNAME}
      - REDIS_PASSWORD=${APP_REDIS__PASSWORD}
      - REDIS_DB=${APP_REDIS__DATABASE_NAME}
    ports:
      - "${APP_REDIS__PORT}:${APP_REDIS__PORT}"
  mailhog:
    image: "mailhog/mailhog"
    networks:
      - server-side
    restart: always
    ports:
      - "${APP_EMAIL__PORT}:${APP_EMAIL__PORT}"
      - "8025:8025"

networks:
  server-side: {
    driver: bridge,
    external: true,
  }

volumes:
  app_data:
    external: false